name: Production deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:unit
  build-and-deploy-to-production:
    needs: run-unit-tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build project artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy project artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --env DATABASE_URL=${{ secrets.DATABASE_URL }}
  run-e2e-tests:
    needs: build-and-deploy-to-production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install postgresql-client
      run: sudo apt install postgresql-client
    - name: Initialize database
      run: psql -f tests/e2e/initialize.sql ${{ secrets.DATABASE_URL }} 
    - name: Install dependencies
      run: npm ci && npx playwright install --with-deps
    - name: Run tests
      run: npm run test:e2e
      env:
        PLAYWRIGHT_TEST_BASE_URL: ${{ vars.PLAYWRIGHT_TEST_BASE_URL }}
